/*
 * LineStyle.java
 *
 * Created on June 8, 2008, 1:51 AM
 */
package ca.cgjennings.apps.arkham.deck.item;

import ca.cgjennings.apps.arkham.AbstractGameComponentEditor;
import ca.cgjennings.apps.arkham.ColourDialog;
import ca.cgjennings.apps.arkham.deck.Deck;
import ca.cgjennings.platform.AgnosticDialog;
import ca.cgjennings.platform.PlatformSupport;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.text.NumberFormat;
import static resources.Language.string;

/**
 *
 * @author Chris Jennings <https://cgjennings.ca/contact>
 */
@SuppressWarnings("serial")
class TextBoxStyleDialog extends javax.swing.JDialog implements AgnosticDialog {

    protected TextBox item;
    NumberFormat formatter;

    /**
     * Creates new form LineStyle
     */
    public TextBoxStyleDialog(java.awt.Frame parent, TextBox line) {
        super(parent, true);
        initComponents();
        getRootPane().setDefaultButton(okBtn);
        DashPattern.createSelector(dashCombo);
        PlatformSupport.makeAgnosticDialog(this, okBtn, cancelBtn);

        this.item = line;
        formatter = NumberFormat.getNumberInstance();
        AbstractGameComponentEditor.localizeComboBoxLabels(endcapCombo, null);
        copyStyleFromItem();
        pack();
    }

    protected void copyStyleFromItem() {
        thicknessField.setValue(item.getOutlineWidth());
        switch (item.getOutlineJoin()) {
            case ROUND:
                endcapCombo.setSelectedIndex(0);
                break;
            case MITER:
                endcapCombo.setSelectedIndex(1);
                break;
            case BEVEL:
                endcapCombo.setSelectedIndex(2);
                break;
        }
        bgColourLabel.setBackground(item.getFillColor());
        colourLabel.setBackground(item.getOutlineColor());
        shrinkCheck.setSelected(item.getShrink());
        justifyCheck.setSelected(item.isTextJustified());
        dashCombo.setSelectedItem(item.getOutlineDashPattern());
    }

    protected boolean copyStyleToItem(TextBox item) {
        float thickness = ((Number) thicknessField.getValue()).floatValue();
        item.setOutlineWidth(thickness);
        switch (endcapCombo.getSelectedIndex()) {
            case 0:
                item.setOutlineJoin(LineJoin.ROUND);
                break;
            case 1:
                item.setOutlineJoin(LineJoin.MITER);
                break;
            case 2:
                item.setOutlineJoin(LineJoin.BEVEL);
                break;
        }
        item.setFillColor(bgColourLabel.getBackground());
        item.setOutlineColor(colourLabel.getBackground());
        item.setShrink(shrinkCheck.isSelected());
        item.setTextJustified(justifyCheck.isSelected());
        item.setOutlineDashPattern((DashPattern) dashCombo.getSelectedItem());
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelBtn = new javax.swing.JButton();
        okBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        endcapCombo = new javax.swing.JComboBox<>();
        dashCombo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        thicknessField = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        colourButton = new javax.swing.JButton();
        colourLabel = new ColourDialog.ColourButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bgColourLabel = new ColourDialog.ColourButton();
        bgColourButton = new javax.swing.JButton();
        shrinkCheck = new javax.swing.JCheckBox();
        justifyCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(string("style-l-text-box")); // NOI18N

        cancelBtn.setText(string("cancel")); // NOI18N

        okBtn.setText(string("style-li-change")); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(string("style-l-border"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(string("style-li-shape"))); // NOI18N

        jLabel1.setText(string("style-li-thickness")); // NOI18N

        jLabel2.setText(string("style-li-points")); // NOI18N

        jLabel3.setText(string("style-li-corners")); // NOI18N

        endcapCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "style-li-round", "style-li-square", "style-li-bevel" }));

        dashCombo.setMaximumRowCount(12);

        jLabel5.setText(string("style-li-dash")); // NOI18N

        thicknessField.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(144.0f), Float.valueOf(0.5f)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(thicknessField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(endcapCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dashCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(thicknessField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(endcapCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(dashCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(string("style-li-appearance"))); // NOI18N

        colourButton.setText(string("style-li-colour")); // NOI18N
        colourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colourButtonActionPerformed(evt);
            }
        });

        colourLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        colourLabel.setContentAreaFilled(false);
        colourLabel.setPreferredSize(new java.awt.Dimension(24, 24));
        colourLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colourButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(colourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(colourButton)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(colourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colourButton))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getSize()-2f));
        jLabel4.setText(string("style-l-disable-border")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel1, jPanel2});

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(string("style-l-text-box"))); // NOI18N

        bgColourLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bgColourLabel.setContentAreaFilled(false);
        bgColourLabel.setPreferredSize(new java.awt.Dimension(24, 24));
        bgColourLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgColourButtonActionPerformed(evt);
            }
        });

        bgColourButton.setText(string("style-li-colour")); // NOI18N
        bgColourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgColourButtonActionPerformed(evt);
            }
        });

        shrinkCheck.setText(string("style-b-shrink-text")); // NOI18N

        justifyCheck.setText(string("style-b-justify-text")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(justifyCheck)
                    .addComponent(shrinkCheck)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(bgColourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bgColourButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bgColourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bgColourButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(shrinkCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(justifyCheck)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelBtn)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelBtn, okBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(okBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void colourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colourButtonActionPerformed
    ColourDialog d = ColourDialog.getSharedDialog();
    d.setSelectedColor(colourLabel.getBackground());
    d.setLocationRelativeTo((Component) evt.getSource());
    d.setVisible(true);
    if (d.getSelectedColor() != null) {
        colourLabel.setBackground(d.getSelectedColor());
    }
}//GEN-LAST:event_colourButtonActionPerformed

private void bgColourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgColourButtonActionPerformed
    ColourDialog d = ColourDialog.getSharedDialog();
    d.setSelectedColor(bgColourLabel.getBackground());
    d.setLocationRelativeTo((Component) evt.getSource());
    d.setVisible(true);
    if (d.getSelectedColor() != null) {
        bgColourLabel.setBackground(d.getSelectedColor());
    }
}//GEN-LAST:event_bgColourButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bgColourButton;
    private javax.swing.JButton bgColourLabel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton colourButton;
    private javax.swing.JButton colourLabel;
    private javax.swing.JComboBox dashCombo;
    private javax.swing.JComboBox<String> endcapCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JCheckBox justifyCheck;
    private javax.swing.JButton okBtn;
    private javax.swing.JCheckBox shrinkCheck;
    private javax.swing.JSpinner thicknessField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void handleOKAction(ActionEvent e) {
        Deck d = item.getPage().getDeck();
        PageItem[] sel = d.getSelection();
        for (int i = 0; i < sel.length; ++i) {
            if (sel[i] instanceof TextBox) {
                // returns false if there is an error in a field
                if (!copyStyleToItem((TextBox) sel[i])) {
                    return;
                }
            }
        }
        item.getPage().getView().repaint();
        dispose();
    }

    @Override
    public void handleCancelAction(ActionEvent e) {
        dispose();
    }

}
