package ca.cgjennings.apps.arkham.dialog;

import ca.cgjennings.apps.arkham.StrangeEons;
import ca.cgjennings.graphics.shapes.VectorImage;
import ca.cgjennings.platform.DesktopIntegration;
import java.io.File;
import java.io.IOException;
import static resources.Language.string;

/**
 * A simple image viewer dialog for vector images modelled on the
 * {@linkplain ImageViewer bitmap image viewer}.
 *
 * @author Chris Jennings <https://cgjennings.ca/contact>
 * @since 3.0
 */
@SuppressWarnings("serial")
public class VectorImageViewer extends javax.swing.JDialog {

    private File original;

    /**
     * Creates a new vector image viewer for the specified image.
     *
     * @param parent the dialog's parent window
     * @param image the vector image to show in the viewer
     * @param modal whether the dialog should block until closed
     */
    public VectorImageViewer(java.awt.Frame parent, VectorImage image, boolean modal) {
        this(parent, image, null, modal);
    }

    /**
     * Creates a new vector image viewer for the specified image.
     *
     * @param parent the dialog's parent window
     * @param image the vector image to show in the viewer
     * @param modal whether the dialog should block until closed
     */
    public VectorImageViewer(java.awt.Window parent, VectorImage image, boolean modal) {
        this(parent, image, null, modal);
    }

    /**
     * Creates a new vector image viewer for the specified image.
     *
     * @param parent the dialog's parent window
     * @param image the vector image to show in the viewer
     * @param original the source file of the image, or <code>null</code>
     * @param modal whether the dialog should block until closed
     */
    public VectorImageViewer(java.awt.Window parent, VectorImage image, File original, boolean modal) {
        super(parent == null ? StrangeEons.getWindow() : parent, string("iv-title"), modal ? ModalityType.APPLICATION_MODAL : ModalityType.MODELESS);
        initComponents();
        getRootPane().setDefaultButton(closeBtn);
        this.original = original;
        editBtn.setVisible(original != null);
        setImage(image);
    }

    /**
     * Sets the vector image to display.
     *
     * @param image the new image
     */
    public void setImage(VectorImage image) {
        viewer.setImage(image);
    }

    /**
     * Returns the vector image being displayed.
     *
     * @return the currently displayed image
     */
    public VectorImage getImage() {
        return viewer.getImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewer = new ca.cgjennings.apps.arkham.VectorImageViewer();
        closeBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        viewer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(128, 128, 128)));

        javax.swing.GroupLayout viewerLayout = new javax.swing.GroupLayout(viewer);
        viewer.setLayout(viewerLayout);
        viewerLayout.setHorizontalGroup(
            viewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        viewerLayout.setVerticalGroup(
            viewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 253, Short.MAX_VALUE)
        );

        closeBtn.setText(string("close")); // NOI18N
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        editBtn.setText(string( "edit-misc" )); // NOI18N
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(editBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeBtn)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {closeBtn, editBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(viewer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeBtn)
                    .addComponent(editBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        try {
            DesktopIntegration.edit(original, this);
            dispose();
        } catch (IOException e) {
            ErrorDialog.displayError(string("app-err-open", original.getName()), e);
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton editBtn;
    private ca.cgjennings.apps.arkham.VectorImageViewer viewer;
    // End of variables declaration//GEN-END:variables

}
