package ca.cgjennings.apps.arkham.editors;

import ca.cgjennings.apps.arkham.AbstractGameComponentEditor;
import ca.cgjennings.apps.arkham.StrangeEons;
import ca.cgjennings.apps.arkham.dialog.prefs.LanguageCodeDescriptor;
import ca.cgjennings.platform.AgnosticDialog;
import ca.cgjennings.platform.PlatformSupport;
import ca.cgjennings.text.LineSorter;
import ca.cgjennings.ui.JIconList;
import ca.cgjennings.ui.JUtilities;
import java.awt.event.ActionEvent;
import java.text.Collator;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import resources.Language;
import static resources.Language.string;

/**
 * Dialog for setting code editor sort options.
 *
 * @author Chris Jennings <https://cgjennings.ca/contact>
 */
@SuppressWarnings("serial")
class SortDialog extends javax.swing.JDialog implements AgnosticDialog {

    public SortDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        getRootPane().setDefaultButton(okBtn);
        PlatformSupport.makeAgnosticDialog(this, okBtn, cancelBtn);
        AbstractGameComponentEditor.localizeComboBoxLabels(orderBox, null);
        orderBox.setSelectedIndex(5);

        DefaultComboBoxModel lazyPlaceholder = new DefaultComboBoxModel();
        lazyPlaceholder.addElement(string("ced-sort-b-use-other-locale"));
        customLocaleCombo.setModel(lazyPlaceholder);

        pack();
    }

    private void initLocaleCombo() {
        // check if the locale combo was already loaded
        if (!(customLocaleCombo.getModel().getElementAt(0) instanceof String)) {
            return;
        }

        JUtilities.showWaitCursor(this);
        try {
            DefaultComboBoxModel m = new DefaultComboBoxModel();
            for (Locale loc : Language.getLocales()) {
                m.addElement(new LanguageCodeDescriptor(loc, false, true));
            }
            customLocaleCombo.setModel(m);
            customLocaleCombo.setSelectedIndex(0);
            pack();
        } finally {
            JUtilities.hideWaitCursor(this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderGroup = new javax.swing.ButtonGroup();
        localeGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        ascOrderBtn = new javax.swing.JRadioButton();
        descOrderBtn = new javax.swing.JRadioButton();
        cancelBtn = new javax.swing.JButton();
        okBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        orderBox = new javax.swing.JComboBox();
        langLabel = new javax.swing.JLabel();
        useUIBtn = new javax.swing.JRadioButton();
        useGameBtn = new javax.swing.JRadioButton();
        useCustomBtn = new javax.swing.JRadioButton();
        customLocaleCombo = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        delDuplicatesCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(string( "ced-sort-ok" )); // NOI18N
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(string( "ced-sort-l-order" ))); // NOI18N

        orderGroup.add(ascOrderBtn);
        ascOrderBtn.setSelected(true);
        ascOrderBtn.setText(string( "ced-sort-ascending" )); // NOI18N

        orderGroup.add(descOrderBtn);
        descOrderBtn.setText(string( "ced-sort-descending" )); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ascOrderBtn)
                    .addComponent(descOrderBtn)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ascOrderBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descOrderBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cancelBtn.setText(string( "cancel" )); // NOI18N

        okBtn.setText(string( "ced-sort-ok" )); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(string( "ced-sort-l-ordering" ))); // NOI18N

        orderBox.setMaximumRowCount(9);
        orderBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ced-sort-0", "ced-sort-1", "ced-sort-2", "ced-sort-3", "ced-sort-4", "ced-sort-5", "ced-sort-6", "ced-sort-7", "ced-sort-8" }));
        orderBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderBoxActionPerformed(evt);
            }
        });

        langLabel.setText(string( "ced-sort-l-locale" )); // NOI18N

        localeGroup.add(useUIBtn);
        useUIBtn.setText(string( "ced-sort-b-use-ui-locale" )); // NOI18N

        localeGroup.add(useGameBtn);
        useGameBtn.setSelected(true);
        useGameBtn.setText(string( "ced-sort-b-use-game-locale" )); // NOI18N

        localeGroup.add(useCustomBtn);
        useCustomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageBtnActionPerformed(evt);
            }
        });

        customLocaleCombo.setFont(customLocaleCombo.getFont().deriveFont(customLocaleCombo.getFont().getSize()-1f));
        customLocaleCombo.setRenderer( new JIconList.IconRenderer() );
        customLocaleCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customLocaleComboFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(langLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(useUIBtn)
                            .addComponent(useGameBtn)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(useCustomBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(customLocaleCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(langLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(useGameBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(useUIBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(useCustomBtn)
                    .addComponent(customLocaleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(string( "ced-sort-l-options" ))); // NOI18N

        delDuplicatesCheck.setText(string( "ced-sort-b-del-duplicate" )); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(delDuplicatesCheck)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(delDuplicatesCheck)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBtn)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelBtn, okBtn});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel1, jPanel3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(okBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

	private void orderBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBoxActionPerformed
            boolean enable = orderBox.getSelectedIndex() != 0;
            langLabel.setEnabled(enable);
            useGameBtn.setEnabled(enable);
            useUIBtn.setEnabled(enable);
	}//GEN-LAST:event_orderBoxActionPerformed

    private void languageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageBtnActionPerformed
        if (useCustomBtn.isSelected()) {
            initLocaleCombo();
        }
    }//GEN-LAST:event_languageBtnActionPerformed

    private void customLocaleComboFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customLocaleComboFocusGained
        useCustomBtn.setSelected(true);
        initLocaleCombo();
    }//GEN-LAST:event_customLocaleComboFocusGained

    public LineSorter getSorter() {
        int sel = orderBox.getSelectedIndex();

        if (sel < 0) {
            return null;
        }

        boolean descending = descOrderBtn.isSelected();
        if (sel == 0) {
            return new LineSorter(descending);
        }

        Locale locale;
        if (useUIBtn.isSelected()) {
            locale = Language.getInterfaceLocale();
        } else if (useGameBtn.isSelected()) {
            locale = Language.getGameLocale();
        } else {
            locale = ((LanguageCodeDescriptor) customLocaleCombo.getSelectedItem()).getLocale();
        }
        if (locale == null) {
            StrangeEons.log.severe("null locale");
            locale = Locale.getDefault();
        }

        final int[] strengths = new int[]{
            Collator.PRIMARY,
            Collator.SECONDARY,
            Collator.TERTIARY,
            Collator.IDENTICAL
        };

        --sel;
        if (sel < 4) {
            return new LineSorter.LocalizedSorter(locale, strengths[sel], descending);
        } else {
            return new LineSorter.SemanticSorter(locale, strengths[sel - 4], descending);
        }
    }

    public boolean getDeleteDuplicates() {
        return delDuplicatesCheck.isSelected();
    }

    public boolean showDialog() {
        ok = false;
        setVisible(true);
        return ok;
    }
    private boolean ok;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ascOrderBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox customLocaleCombo;
    private javax.swing.JCheckBox delDuplicatesCheck;
    private javax.swing.JRadioButton descOrderBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel langLabel;
    private javax.swing.ButtonGroup localeGroup;
    private javax.swing.JButton okBtn;
    private javax.swing.JComboBox orderBox;
    private javax.swing.ButtonGroup orderGroup;
    private javax.swing.JRadioButton useCustomBtn;
    private javax.swing.JRadioButton useGameBtn;
    private javax.swing.JRadioButton useUIBtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void handleOKAction(ActionEvent e) {
        ok = true;
        dispose();
    }

    @Override
    public void handleCancelAction(ActionEvent e) {
        dispose();
    }
}
