package ca.cgjennings.apps.arkham.deck.item;

import ca.cgjennings.apps.arkham.ColourDialog;
import java.awt.Color;
import java.awt.Component;
import static resources.Language.string;

/**
 * The style panel for editing lines and paths.
 *
 * @author Chris Jennings <https://cgjennings.ca/contact>
 * @since 3.0
 */
@SuppressWarnings("serial")
class LineStylePanel extends AbstractStylePanel<LineStyle> implements LineStyle {

    /**
     * Creates new line style editing panel.
     */
    public LineStylePanel() {
        initComponents();
        DashPattern.createSelector(dashCombo);
    }

    @Override
    public String getTitle() {
        return string("stlye-l-title-line");
    }

    @Override
    public Color getLineColor() {
        return colourLabel.getBackground();
    }

    @Override
    public void setLineColor(Color borderColor) {
        colourLabel.setBackground(borderColor);
    }

    @Override
    public float getLineWidth() {
        return ((Number) thicknessField.getValue()).floatValue();
    }

    @Override
    public void setLineWidth(float borderWidth) {
        thicknessField.setValue(borderWidth);
    }

    @Override
    public DashPattern getLineDashPattern() {
        return (DashPattern) dashCombo.getSelectedItem();
    }

    @Override
    public void setLineDashPattern(DashPattern pat) {
        dashCombo.setSelectedItem(pat);
    }

    @Override
    public void setLineCap(LineCap cap) {
        capSelector.setSelectedItem(cap);
    }

    @Override
    public LineCap getLineCap() {
        return capSelector.getSelectedItem();
    }

    @Override
    public void setLineJoin(LineJoin join) {
        joinSelector.setSelectedItem(join);
    }

    @Override
    public LineJoin getLineJoin() {
        return joinSelector.getSelectedItem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
        colourButton = new javax.swing.JButton();
        colourLabel = new ColourDialog.ColourButton();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dashCombo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        thicknessField = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        capSelector = new ca.cgjennings.apps.arkham.deck.item.LineCapSelector();
        joinSelector = new ca.cgjennings.apps.arkham.deck.item.LineJoinSelector();

        colourButton.setText(string("style-li-colour")); // NOI18N
        colourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colourControlActionPerformed(evt);
            }
        });

        colourLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        colourLabel.setContentAreaFilled(false);
        colourLabel.setPreferredSize(new java.awt.Dimension(24, 24));
        colourLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colourControlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(colourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(colourButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(colourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colourButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText(string("style-li-thickness")); // NOI18N

        jLabel4.setText(string("style-li-points")); // NOI18N

        jLabel5.setText(string("style-li-corners")); // NOI18N

        dashCombo.setMaximumRowCount(12);
        dashCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorActionPerformed(evt);
            }
        });

        jLabel6.setText(string("style-li-dash")); // NOI18N

        thicknessField.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.25f), Float.valueOf(0.25f), Float.valueOf(144.0f), Float.valueOf(0.1f)));
        thicknessField.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                thicknessFieldStateChanged(evt);
            }
        });

        jLabel7.setText(string("style-li-endcap")); // NOI18N

        capSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorActionPerformed(evt);
            }
        });

        joinSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(joinSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(thicknessField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(capSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(thicknessField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(joinSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(capSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(dashCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void colourControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colourControlActionPerformed
        ColourDialog d = ColourDialog.getSharedDialog();
        d.setSelectedColor(colourLabel.getBackground());
        d.setLocationRelativeTo((Component) evt.getSource());
        d.setVisible(true);
        if (d.getSelectedColor() != null) {
            colourLabel.setBackground(d.getSelectedColor());
            styleChanged();
        }
    }//GEN-LAST:event_colourControlActionPerformed

    private void thicknessFieldStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_thicknessFieldStateChanged
        styleChanged();
    }//GEN-LAST:event_thicknessFieldStateChanged

    private void selectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectorActionPerformed
        styleChanged();
    }//GEN-LAST:event_selectorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ca.cgjennings.apps.arkham.deck.item.LineCapSelector capSelector;
    private javax.swing.JButton colourButton;
    private javax.swing.JButton colourLabel;
    private javax.swing.JComboBox dashCombo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private ca.cgjennings.apps.arkham.deck.item.LineJoinSelector joinSelector;
    private javax.swing.JSpinner thicknessField;
    // End of variables declaration//GEN-END:variables

    @Override
    public int getPanelGroup() {
        return 1_200;
    }
}
