package ca.cgjennings.apps.arkham.deck;

import java.io.File;
import static resources.Language.string;
import resources.ResourceKit;

/**
 * A dialog that allows the user to locate missing deck files.
 *
 * @author Chris Jennings <https://cgjennings.ca/contact>
 * @since 1.65
 */
@SuppressWarnings("serial")
final class DeckDeserializationDialog extends javax.swing.JDialog implements java.awt.event.ActionListener {

    /**
     * Creates new form DeckDeserializationDialog
     */
    public DeckDeserializationDialog(java.awt.Frame parent, boolean modal, String name, String path) {
        super(parent, modal);
        initComponents();
        // String fileName = new File( path ).getName();
        label.setText(string("de-l-fix-file", name, path));

        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        locateBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(string("de-l-title-fix-file")); // NOI18N

        label.setText(string("de-l-fix-file")); // NOI18N
        label.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        locateBtn.setText(string("de-b-fix-file")); // NOI18N
        locateBtn.addActionListener(this);

        cancelBtn.setText(string("cancel")); // NOI18N
        cancelBtn.addActionListener(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(locateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBtn))
                    .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelBtn, locateBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(locateBtn))
                .addContainerGap())
        );

        label.getAccessibleContext().setAccessibleName("<html><b>Unable to Locate One of the Card Files Used in this Deck</b><br> <br>The card <i>%s</i> was not found at:<br><pre>%s</pre>");

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == locateBtn) {
            DeckDeserializationDialog.this.locateBtnActionPerformed(evt);
        }
        else if (evt.getSource() == cancelBtn) {
            DeckDeserializationDialog.this.cancelBtnActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents
    private void locateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locateBtnActionPerformed
        file = ResourceKit.showOpenDialog(this);
        dispose();
    }//GEN-LAST:event_locateBtnActionPerformed
    private File file;

    public File getReplacementFile() {
        return file;
    }

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        file = null;
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel label;
    private javax.swing.JButton locateBtn;
    // End of variables declaration//GEN-END:variables
}
