package ca.cgjennings.apps.arkham;

import ca.cgjennings.platform.AgnosticDialog;
import ca.cgjennings.platform.PlatformSupport;
import java.awt.event.ActionEvent;
import javax.swing.JComponent;
import javax.swing.JRadioButton;
import javax.swing.text.JTextComponent;
import static resources.Language.string;

/**
 * Dialog for choosing block and paragraph alignment.
 *
 * @author Chris Jennings <https://cgjennings.ca/contact>
 * @since 3.0
 */
@SuppressWarnings("serial")
final public class ParagraphDialog extends javax.swing.JDialog implements AgnosticDialog {

    /**
     * Creates new form ParagraphDialog
     */
    public ParagraphDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        getRootPane().setDefaultButton(okBtn);
        PlatformSupport.makeAgnosticDialog(this, okBtn, cancelBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hGroup = new javax.swing.ButtonGroup();
        vGroup = new javax.swing.ButtonGroup();
        jGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        LBtn = new javax.swing.JRadioButton();
        CBtn = new javax.swing.JRadioButton();
        RBtn = new javax.swing.JRadioButton();
        dncH = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        TBtn = new javax.swing.JRadioButton();
        MBtn = new javax.swing.JRadioButton();
        BBtn = new javax.swing.JRadioButton();
        UBtn = new javax.swing.JRadioButton();
        JBtn = new javax.swing.JRadioButton();
        dncV = new javax.swing.JRadioButton();
        dncJ = new javax.swing.JRadioButton();
        cancelBtn = new javax.swing.JButton();
        okBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(string( "para-l-title" )); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(string( "para-l-halign" ))); // NOI18N

        hGroup.add(LBtn);
        LBtn.setText(string( "para-b-left" )); // NOI18N

        hGroup.add(CBtn);
        CBtn.setText(string( "para-b-centre" )); // NOI18N

        hGroup.add(RBtn);
        RBtn.setText(string( "para-b-right" )); // NOI18N

        hGroup.add(dncH);
        dncH.setSelected(true);
        dncH.setText(string( "ffd-l-no-change" )); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CBtn)
                    .addComponent(RBtn)
                    .addComponent(LBtn)
                    .addComponent(dncH))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(dncH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(string( "para-l-valign" ))); // NOI18N

        vGroup.add(TBtn);
        TBtn.setText(string( "para-b-top" )); // NOI18N

        vGroup.add(MBtn);
        MBtn.setText(string( "para-b-middle" )); // NOI18N

        vGroup.add(BBtn);
        BBtn.setText(string( "para-b-bottom" )); // NOI18N

        jGroup.add(UBtn);
        UBtn.setText(string( "para-b-ragged" )); // NOI18N

        jGroup.add(JBtn);
        JBtn.setText(string( "para-b-justify" )); // NOI18N

        vGroup.add(dncV);
        dncV.setSelected(true);
        dncV.setText(string( "ffd-l-no-change" )); // NOI18N

        jGroup.add(dncJ);
        dncJ.setSelected(true);
        dncJ.setText(string( "ffd-l-no-change" )); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BBtn)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dncV)
                            .addComponent(TBtn)
                            .addComponent(MBtn))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBtn)
                            .addComponent(UBtn)
                            .addComponent(dncJ))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dncV)
                    .addComponent(dncJ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TBtn)
                    .addComponent(UBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MBtn)
                    .addComponent(JBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BBtn))
        );

        cancelBtn.setText(string( "cancel" )); // NOI18N

        okBtn.setText(string( "para-l-ok" )); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(okBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(okBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showDialog(JComponent commandTarget) {
        this.target = commandTarget;
        setVisible(true);
    }
    private JComponent target;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BBtn;
    private javax.swing.JRadioButton CBtn;
    private javax.swing.JRadioButton JBtn;
    private javax.swing.JRadioButton LBtn;
    private javax.swing.JRadioButton MBtn;
    private javax.swing.JRadioButton RBtn;
    private javax.swing.JRadioButton TBtn;
    private javax.swing.JRadioButton UBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JRadioButton dncH;
    private javax.swing.JRadioButton dncJ;
    private javax.swing.JRadioButton dncV;
    private javax.swing.ButtonGroup hGroup;
    private javax.swing.ButtonGroup jGroup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton okBtn;
    private javax.swing.ButtonGroup vGroup;
    // End of variables declaration//GEN-END:variables

    public static void adjustParagraphSettings(JComponent target, int hsel, int vsel, int jsel) {
        if (target instanceof JTextComponent) {
            JTextComponent ed = (JTextComponent) target;
            String text = ed.getText();

            // make start <= end
            boolean swapped = false;
            int start = ed.getSelectionStart();
            int end = ed.getSelectionEnd();
            if (start > end) {
                int temp = start;
                start = end;
                end = temp;
                swapped = true;
            }

            // want at least one line break to split text into chunks
            // extend selection to nearest line breaks
            for (; start > 0 && text.charAt(start - 1) != '\n'; --start);
            for (; end < text.length() - 1 && text.charAt(end) != '\n'; ++end);

            String left = text.substring(0, start);
            String middle = text.substring(start, end);
            String right = text.substring(end);

            // remove any existing vertical tags anywhere in the text,
            // and any existing horizontal tags in the selected paragraph(s)
            // user changing vertical selection
            if (vsel >= 0) {
                left = remove(left, vtags);
                middle = remove(middle, vtags);
                right = remove(right, vtags);
            }
            if (jsel >= 0) {
                left = remove(left, jtags);
                middle = remove(middle, jtags);
                right = remove(right, jtags);
            }

            // user changing horizontal selection
            if (hsel >= 0) {
                middle = remove(middle, htags);
            }

            // determine tags for start of block (vtag) and selection (htag)
            String vtag = "";
            if (vsel >= 0) {
                vtag = vtags[vsel];
            }
            String jtag = "";
            if (jsel >= 0) {
                jtag = jtags[jsel];
            }
            vtag += jtag;

            String htag = "";
            if (hsel >= 0) {
                htag = htags[hsel];
            }

            text = vtag + left + htag + middle + right;
            start = vtag.length() + left.length() + htag.length();
            end = start + middle.length();

            ed.setText(text);
            if (swapped) {
                ed.select(end, start);
            } else {
                ed.select(start, end);
            }
        } else if (MarkupTargetFactory.isValidTarget(target, false)) {
            // fallback for code editor (assumes putting this in a string)
            // and one-line case of other targets
            String markup = "";
            if (vsel >= 0) {
                markup = vtags[vsel];
            }
            if (jsel >= 0) {
                markup += jtags[jsel];
            }
            if (hsel >= 0) {
                markup += htags[hsel];
            }
            MarkupTargetFactory.createMarkupTarget(target, false)
                    .tagSelectedText(markup, "", false);
        }
    }

    @Override
    @SuppressWarnings("empty-statement")
    public void handleOKAction(ActionEvent e) {
        int jsel = selection(JBtn, UBtn, null);
        int vsel = selection(TBtn, MBtn, BBtn);
        int hsel = selection(LBtn, CBtn, RBtn);
        adjustParagraphSettings(target, hsel, vsel, jsel);
        dispose();
    }

    private static int selection(JRadioButton t, JRadioButton m, JRadioButton b) {
        if (t.isSelected()) {
            return 0;
        }
        if (m.isSelected()) {
            return 1;
        }
        if (b != null && b.isSelected()) {
            return 2;
        }
        return -1;
    }

    private static String remove(String s, String[] x) {
        for (int i = 0; i < x.length; ++i) {
            s = s.replaceAll("(?i)" + x[i], "");
        }
        return s;
    }

    private static final String[] vtags = new String[]{"<top>", "<middle>", "<bottom>"};
    private static final String[] jtags = new String[]{"<justified>", "<ragged>"};
    private static final String[] htags = new String[]{"<left>", "<center>", "<right>"};

    @Override
    public void handleCancelAction(ActionEvent e) {
        dispose();
    }

}
