package ca.cgjennings.apps.arkham.project;

import ca.cgjennings.apps.arkham.StrangeEons;
import ca.cgjennings.ui.textedit.CodeEditorBase;
import ca.cgjennings.ui.theme.Palette;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.font.TextAttribute;
import java.util.Collection;
import java.util.Collections;

import javax.swing.JLabel;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import static resources.Language.string;

/**
 * Dialog that displays default file diffs.
 *
 * @author Chris Jennings <https://cgjennings.ca/contact>
 * @see CompareFiles
 */
@SuppressWarnings("serial")
class DiffDialog extends javax.swing.JDialog {

    /**
     * Creates new form DiffDialog
     */
    public DiffDialog(String f1Name, String f2Name, Collection<CompareFiles.DiffLine> diff) {
        super(StrangeEons.getWindow(), false);
        initComponents();
        lhsLabel.setText(f1Name);
        rhsLabel.setText(f2Name);
        
        diffPanel.setLayout(new GridLayout(diff.size(), 1));
        
        Font fontUnchanged = new CodeEditorBase().getFont();
        Font fontInserted = fontUnchanged.deriveFont(Font.ITALIC);
        Font fontDeleted = fontUnchanged.deriveFont(Collections.singletonMap(TextAttribute.STRIKETHROUGH, TextAttribute.STRIKETHROUGH_ON));

        Border b = new EmptyBorder(0,4,1,4);

        Color deleted = Palette.get.pastel.translucent.pink;
        Color deletedBackground = Palette.get.dark.opaque.red;

        Color inserted = Palette.get.light.translucent.white;
        Color insertedBackground = Palette.get.dark.opaque.green;
        
        for (CompareFiles.DiffLine li : diff) {
            JLabel line = new JLabel(li.text);
            Font font = fontUnchanged;
            Color fg = null;
            Color bg = null;            
            line.setBorder(b);
            if (li.state < 0) {
                bg = deletedBackground;
                fg = deleted;
                font = fontDeleted;
            } else if (li.state > 0) {
                bg = insertedBackground;
                fg = inserted;
                font = fontInserted;
            }
            line.setFont(font);
            if (bg != null) {
                line.setOpaque(true);
                line.setBackground(bg);
                line.setForeground(fg);
            }
            diffPanel.add(line);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        closeBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lhsLabel = new javax.swing.JLabel();
        rhsLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        diffPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(string( "pa-diff" )); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, java.awt.Color.gray));

        closeBtn.setText(string( "close" )); // NOI18N
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(531, Short.MAX_VALUE)
                .addComponent(closeBtn)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeBtn)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.gray));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        lhsLabel.setText("f1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 8);
        jPanel2.add(lhsLabel, gridBagConstraints);

        rhsLabel.setText("f2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 8, 2, 2);
        jPanel2.add(rhsLabel, gridBagConstraints);

        jLabel3.setText(":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel2.add(jLabel3, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout diffPanelLayout = new javax.swing.GroupLayout(diffPanel);
        diffPanel.setLayout(diffPanelLayout);
        diffPanelLayout.setHorizontalGroup(
            diffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        diffPanelLayout.setVerticalGroup(
            diffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(diffPanel);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
            dispose();
	}//GEN-LAST:event_closeBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JPanel diffPanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lhsLabel;
    private javax.swing.JLabel rhsLabel;
    // End of variables declaration//GEN-END:variables
}
