name: Synch Tags

on:
  push:
    tags:
      - 'v*'

jobs:
  sync-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Create same tag on doc repository
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tagName = context.ref.replace('refs/tags/', '');
            const repo = 'CGJennings/se3docs';
            const owner = 'CGJennings';
            const sha = context.sha;
            await github.git.createRef({
              owner,
              repo,
              ref: `refs/tags/${tagName}`,
              sha
            });